import React, { useState, useEffect, FormEvent, DragEvent } from 'react';
import {
  HelpCircle,
  Mail,
  ChevronDown,
  ChevronUp,
  CheckCircle,
  UploadCloud,
  FileText,
  AlertCircle,
  Clock,
  ShieldCheck,
  RefreshCw
} from 'lucide-react';

interface DbFile {
  id: string;
  name: string;
  sizeKb: number;
  uploadedAt: string;
  category: string;
  url: string;
  status: string;
}

export default function SupportView() {
  const [expandedFaq, setExpandedFaq] = useState<number | null>(0);
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    subject: 'Billing Inquiry',
    message: '',
  });

  // File Upload states
  const [files, setFiles] = useState<DbFile[]>([]);
  const [loadingFiles, setLoadingFiles] = useState(false);
  const [uploadCategory, setUploadCategory] = useState('Utility Bill Data');
  const [uploading, setUploading] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const [uploadSuccess, setUploadSuccess] = useState('');

  const faqs = [
    {
      q: 'What is a Power Purchase Agreement (PPA) standard contract?',
      a: 'Under standard Sunzero PPA agreements, our teams install rooftop solar arrays at absolutely zero upfront purchasing cost. You pay for the green electricity generated by panels at a locked, static index rate that sits up to 45% cheaper than traditional public grid tariffs.',
    },
    {
      q: 'How does dynamic net utility metering transfer work?',
      a: 'When your panels produce more electricity than your residential appliances draw in real-time, the excess generation feeds back into the shared community power grid. Net meters count these exports, crediting your household or batteries.',
    },
    {
      q: 'What does the Synchronized state on the Live Flow dashboard symbolize?',
      a: 'The Synchronized badge indicates that your local virtual dashboard is actively connected to the physical Sunzero smart inverter microprocessors over a secure IoT SSL channel, updating telemetry counters every few seconds with zero lag.',
    },
    {
      q: 'How can I schedule high-power appliances to maximum benefit?',
      a: 'Check our Load Profiling analyser! Simply shift heavy duty appliance demands like EV chargers, pool filtration pumps, and washer-dryer cycles into midday solar-peak periods (11 AM to 3 PM) to completely bypass grid consumption liabilities.',
    },
  ];

  const handleFormSubmit = (e: FormEvent) => {
    e.preventDefault();
    setFormSubmitted(true);
    setTimeout(() => {
      setFormSubmitted(false);
      setFormData({ name: '', email: '', subject: 'Billing Inquiry', message: '' });
    }, 6000);
  };

  // Fetch file locker listings
  const fetchFiles = async () => {
    setLoadingFiles(true);
    try {
      const response = await fetch('/api/files/list');
      const data = await response.json();
      if (data.files) {
        setFiles(data.files);
      }
    } catch (err) {
      console.error('Error fetching files:', err);
    } finally {
      setLoadingFiles(false);
    }
  };

  useEffect(() => {
    fetchFiles();
  }, []);

  // Process actual file uploads to server
  const processUpload = async (fileName: string, fileSizeKb: number) => {
    setUploading(true);
    setUploadSuccess('');
    try {
      const response = await fetch('/api/files/upload', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: fileName,
          sizeKb: fileSizeKb,
          category: uploadCategory,
          base64Content: 'simulated-base64-file-string'
        })
      });
      const data = await response.json();
      if (data.success) {
        setUploadSuccess(`Document "${fileName}" successfully uploaded and locked.`);
        fetchFiles();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setUploading(false);
    }
  };

  // Click file upload handler
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      const sizeKb = Math.round(selectedFile.size / 1024);
      processUpload(selectedFile.name, sizeKb);
    }
  };

  // Drag and drop event handlers
  const handleDrag = (e: DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  };

  const handleDrop = (e: DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const droppedFile = e.dataTransfer.files[0];
      const sizeKb = Math.round(droppedFile.size / 1024);
      processUpload(droppedFile.name, sizeKb);
    }
  };

  return (
    <div id="support-view-container" className="space-y-8 animate-fade-in text-wrap">
      
      {/* Page Header */}
      <section className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-gray-100 pb-4">
        <div>
          <span className="bg-primary/10 text-primary text-[10px] uppercase font-black px-2.5 py-1 rounded-full tracking-wider border border-primary/20">
            Assistance & Verification Suite
          </span>
          <h2 className="text-3xl font-extrabold text-on-surface tracking-tight mt-2 font-sans font-sans">Customer Support & Upload Locker</h2>
          <p className="text-sm text-secondary mt-1">
            Access solar education logs, submit operational inquiry tickets, or upload interconnection bills for compliance review.
          </p>
        </div>
      </section>

      {/* Main Grid: FAQs on left + Request Inquiry Form on right */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* FAQs and Document Uploader (Col Span 8) */}
        <div className="lg:col-span-8 space-y-6">
          
          {/* FAQ panel */}
          <div className="bg-white rounded-2xl border border-outline-variant p-6 hover:shadow-md transition-all space-y-4">
            <h3 className="text-sm font-black uppercase tracking-wider text-on-surface flex items-center gap-2 mb-2 border-b border-gray-50 pb-2">
              <HelpCircle className="w-5 h-5 text-primary" /> Solar Smart Inquiries List
            </h3>

            <div className="space-y-3">
              {faqs.map((faq, idx) => {
                const isOpen = expandedFaq === idx;
                return (
                  <div
                    key={idx}
                    className={`border rounded-xl transition-all ${
                      isOpen ? 'border-primary bg-neutral-50/15' : 'border-outline-variant bg-white'
                    }`}
                  >
                    <div
                      onClick={() => setExpandedFaq(isOpen ? null : idx)}
                      className="flex justify-between items-center p-4 cursor-pointer select-none"
                    >
                      <h4 className="text-xs font-black tracking-wide text-on-surface leading-snug">{faq.q}</h4>
                      {isOpen ? <ChevronDown className="w-4 h-4 text-primary shrink-0" /> : <ChevronDown className="w-4 h-4 text-secondary shrink-0" />}
                    </div>

                    {isOpen && (
                      <div className="p-4 border-t border-outline-variant bg-white text-xs text-secondary leading-relaxed rounded-b-xl animate-fade-in font-sans font-medium">
                        {faq.a}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Interactive Document Upload Locker */}
          <div className="bg-white rounded-2xl border border-outline-variant p-6 hover:shadow-md transition-all space-y-6">
            <div className="flex justify-between items-center border-b border-gray-100 pb-3">
              <div>
                <h3 className="text-sm font-black uppercase tracking-wider text-on-surface flex items-center gap-2">
                  <UploadCloud className="w-5 h-5 text-primary" /> Interconnection Document Locker
                </h3>
                <p className="text-[11px] text-secondary mt-0.5">Submit municipal permits, PG&E bill sheets, or signed contracts to the cloud locker.</p>
              </div>
              <button onClick={fetchFiles} className="text-slate-400 hover:text-primary transition-colors cursor-pointer">
                <RefreshCw className="w-3.5 h-3.5" />
              </button>
            </div>

            {uploadSuccess && (
              <div className="p-3 bg-emerald-50 border border-emerald-100 text-emerald-800 text-xs font-bold rounded-xl">
                {uploadSuccess}
              </div>
            )}

            {/* Drag & Drop Upload Zone */}
            <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
              
              <div className="md:col-span-5 space-y-4">
                <div>
                  <label className="block text-[10px] uppercase font-bold text-secondary mb-1">Target Classification</label>
                  <select
                    value={uploadCategory}
                    onChange={(e) => setUploadCategory(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-xs font-semibold focus:outline-none"
                  >
                    <option value="Utility Bill Data">Utility Bill Data (CSV / PDF)</option>
                    <option value="Interconnection Approval">Interconnection Approval</option>
                    <option value="Municipal Permit">Municipal Zoning Permit</option>
                    <option value="General Agreement">PPA Signed Agreement</option>
                  </select>
                </div>

                <div
                  onDragEnter={handleDrag}
                  onDragOver={handleDrag}
                  onDragLeave={handleDrag}
                  onDrop={handleDrop}
                  className={`border-2 border-dashed rounded-2xl p-6 text-center transition-all cursor-pointer flex flex-col items-center justify-center relative ${
                    dragActive ? 'border-primary bg-orange-50/30' : 'border-slate-200 hover:border-primary bg-slate-50'
                  }`}
                >
                  <UploadCloud className="w-8 h-8 text-secondary mb-2" />
                  <p className="text-xs font-bold text-on-surface">Drag & Drop file here</p>
                  <p className="text-[10px] text-secondary mt-1">or click to choose locally</p>
                  
                  {/* Native file input */}
                  <input
                    type="file"
                    id="doc-file-upload"
                    onChange={handleFileChange}
                    className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
                    accept=".pdf,.csv,.doc,.docx"
                  />
                </div>
                {uploading && (
                  <p className="text-[10px] text-primary font-bold animate-pulse text-center">Uploading verification packet to Sunzero core...</p>
                )}
              </div>

              {/* Uploaded Documents List */}
              <div className="md:col-span-7 space-y-3">
                <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 block mb-1">Uploaded Certificates</span>
                
                {loadingFiles ? (
                  <div className="text-center py-6 text-xs text-[#5d5f5f]">Querying files bucket...</div>
                ) : files.length === 0 ? (
                  <div className="text-center py-8 text-xs text-secondary italic bg-slate-50 rounded-xl border border-slate-100">No verification documents uploaded.</div>
                ) : (
                  <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
                    {files.map((file) => (
                      <div key={file.id} className="p-3 bg-slate-50 border border-slate-100 rounded-xl flex items-center justify-between text-xs font-mono">
                        <div className="flex items-center gap-2.5">
                          <div className="w-8 h-8 rounded-lg bg-orange-100 flex items-center justify-center text-primary shrink-0">
                            <FileText className="w-4 h-4" />
                          </div>
                          <div>
                            <p className="font-bold text-on-surface truncate max-w-xs">{file.name}</p>
                            <span className="text-[9.5px] text-secondary leading-none block mt-0.5 font-sans font-medium uppercase text-slate-500">
                              {file.category} • {file.sizeKb} KB
                            </span>
                          </div>
                        </div>

                        <div className="flex items-center gap-1.5 font-sans">
                          <span className="bg-emerald-50 border border-emerald-100 text-emerald-800 text-[9px] font-black px-1.5 py-0.5 rounded uppercase">
                            Verified
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Inquiry Care Form (Col Span 4) */}
        <div className="lg:col-span-4 bg-white rounded-2xl border border-outline-variant p-6 hover:shadow-lg transition-all flex flex-col justify-between">
          <div className="space-y-4">
            <h4 className="font-bold text-on-surface uppercase tracking-wider flex items-center gap-1.5 border-b border-outline-variant pb-2">
              <Mail className="w-4 h-4 text-primary" /> Care Inquiry Form
            </h4>

            {formSubmitted ? (
              <div className="p-6 bg-emerald-50 border border-emerald-150 rounded-xl text-center space-y-3 animate-fade-in py-12">
                <CheckCircle className="w-12 h-12 text-emerald-600 mx-auto animate-bounce" />
                <p className="font-extrabold text-emerald-800 text-sm">Message Dispatch Success!</p>
                <p className="text-[11px] text-secondary leading-relaxed">
                  Our Sunzero support engineering crew will review your notes and reply over email within the next 2 hours.
                </p>
              </div>
            ) : (
              <form onSubmit={handleFormSubmit} className="space-y-4 text-xs">
                <div className="space-y-1">
                  <label htmlFor="support-name" className="font-bold text-secondary uppercase tracking-wider block">
                    Your Name
                  </label>
                  <input
                    id="support-name"
                    type="text"
                    required
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    className="w-full bg-gray-50 border border-outline-variant/60 rounded-xl p-2.5 text-on-surface focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary text-xs"
                    placeholder="Jane Cooper"
                  />
                </div>

                <div className="space-y-1">
                  <label htmlFor="support-email" className="font-bold text-secondary uppercase tracking-wider block">
                    Email Address
                  </label>
                  <input
                    id="support-email"
                    type="email"
                    required
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    className="w-full bg-gray-50 border border-outline-variant/60 rounded-xl p-2.5 text-on-surface focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary text-xs"
                    placeholder="jane@sunzero.io"
                  />
                </div>

                <div className="space-y-1">
                  <label htmlFor="support-subject" className="font-bold text-secondary uppercase tracking-wider block">
                    Subject Topic
                  </label>
                  <select
                    id="support-subject"
                    value={formData.subject}
                    onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                    className="w-full bg-gray-50 border border-outline-variant/60 rounded-xl p-2.5 text-on-surface focus:outline-none text-xs select-none font-semibold"
                  >
                    <option>Billing Inquiry</option>
                    <option>Hardware Installation Maintenance</option>
                    <option>Grid Connection Surcharge</option>
                    <option>General Care Feedback</option>
                  </select>
                </div>

                <div className="space-y-1">
                  <label htmlFor="support-message" className="font-bold text-secondary uppercase tracking-wider block">
                    Inquiry Details
                  </label>
                  <textarea
                    id="support-message"
                    required
                    rows={4}
                    value={formData.message}
                    onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                    className="w-full bg-gray-50 border border-outline-variant/60 rounded-xl p-2.5 text-on-surface focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary text-xs"
                    placeholder="Please write details about your support request..."
                  />
                </div>

                <button
                  id="support-submit-button"
                  type="submit"
                  className="w-full bg-primary text-white hover:bg-[#803100] py-3 rounded-xl font-bold text-xs cursor-pointer transition-all uppercase tracking-wider shadow-md"
                >
                  Send Inquiry Message
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
