import { useState, FormEvent } from 'react';
import { HelpCircle, Mail, Phone, ExternalLink, ChevronDown, ChevronUp, CheckCircle } from 'lucide-react';

export default function SupportView() {
  const [expandedFaq, setExpandedFaq] = useState<number | null>(0);
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    subject: 'Billing Inquiry',
    message: '',
  });

  const faqs = [
    {
      q: 'What is a Power Purchase Agreement (PPA) standard contract?',
      a: 'Under standard Sunzero PPA agreements, our teams install rooftop solar arrays at absolutely zero upfront purchasing cost. You pay for the green electricity generated by panels at a locked, static index rate that sits up to 45% cheaper than traditional public grid tariffs.',
    },
    {
      q: 'How does dynamic net utility metering transfer work?',
      a: 'When your panels produce more electricity than your residential appliances draw in real-time, the excess generation feeds back into the shared community power grid. Net meters count these exports, crediting your household or batteries.',
    },
    {
      q: 'What does the Synchronized state on the Live Flow dashboard symbolize?',
      a: 'The Synchronized badge indicates that your local virtual dashboard is actively connected to the physical Sunzero smart inverter microprocessors over a secure IoT SSL channel, updating telemetry counters every few seconds with zero lag.',
    },
    {
      q: 'How can I schedule high-power appliances to maximum benefit?',
      a: 'Check our Load Profiling analyser! Simply shift heavy duty appliance demands like EV chargers, pool filtration pumps, and washer-dryer cycles into midday solar-peak periods (11 AM to 3 PM) to completely bypass grid consumption liabilities.',
    },
  ];

  const handleFormSubmit = (e: FormEvent) => {
    e.preventDefault();
    setFormSubmitted(true);
    setTimeout(() => {
      setFormSubmitted(false);
      setFormData({ name: '', email: '', subject: 'Billing Inquiry', message: '' });
    }, 6000);
  };

  return (
    <div id="support-view-container" className="space-y-8 animate-fade-in text-wrap">
      {/* Page Header */}
      <section className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-3xl font-extrabold text-on-surface tracking-tight">Customer Care Support</h2>
          <p className="text-sm text-secondary mt-1">
            Access FAQs or file formal service maintenance requests directly with our regional operation centers.
          </p>
        </div>
      </section>

      {/* Main Grid: FAQs on left + Request Inquiry Form on right */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* FAQs section */}
        <div className="bg-white rounded-xl border border-outline-variant p-6 lg:col-span-8 hover:shadow-lg transition-all space-y-4">
          <h3 className="text-lg font-bold text-on-surface flex items-center gap-2 mb-4">
            <HelpCircle className="w-5 h-5 text-primary" /> Frequently Answered Questions
          </h3>

          <div className="space-y-3">
            {faqs.map((faq, idx) => {
              const isOpen = expandedFaq === idx;
              return (
                <div
                  key={idx}
                  className={`border rounded-xl transition-all ${
                    isOpen ? 'border-primary bg-neutral-50/15' : 'border-outline-variant bg-white'
                  }`}
                >
                  <div
                    onClick={() => setExpandedFaq(isOpen ? null : idx)}
                    className="flex justify-between items-center p-4 cursor-pointer select-none"
                  >
                    <h4 className="text-xs font-extrabold text-on-surface leading-snug">{faq.q}</h4>
                    {isOpen ? <ChevronUp className="w-4 h-4 text-primary" /> : <ChevronDown className="w-4 h-4 text-secondary" />}
                  </div>

                  {isOpen && (
                    <div className="p-4 border-t border-outline-variant bg-white text-xs text-secondary leading-relaxed rounded-b-xl animate-fade-in">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Inquiry form */}
        <div className="bg-white rounded-xl border border-outline-variant p-6 lg:col-span-4 hover:shadow-lg transition-all flex flex-col justify-between">
          <div className="space-y-4">
            <h4 className="font-bold text-on-surface uppercase tracking-wider flex items-center gap-1.5 border-b border-outline-variant pb-2">
              <Mail className="w-4 h-4 text-primary" /> Care Inquiry Form
            </h4>

            {formSubmitted ? (
              <div className="p-6 bg-emerald-50 border border-emerald-150 rounded-xl text-center space-y-3 animate-fade-in py-12">
                <CheckCircle className="w-12 h-12 text-emerald-600 mx-auto animate-bounce" />
                <p className="font-extrabold text-emerald-800 text-sm">Message Dispatch Success!</p>
                <p className="text-[11px] text-secondary leading-relaxed">
                  Our Sunzero support engineering crew will review your notes and reply over email within the next 2 hours.
                </p>
              </div>
            ) : (
              <form onSubmit={handleFormSubmit} className="space-y-4 text-xs">
                {/* Field 1: Name */}
                <div className="space-y-1">
                  <label htmlFor="support-name" className="font-bold text-secondary uppercase tracking-wider block">
                    Your Name
                  </label>
                  <input
                    id="support-name"
                    type="text"
                    required
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    className="w-full bg-gray-50 border border-outline-variant/60 rounded-lg p-2.5 text-on-surface focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary text-xs"
                    placeholder="Alex Rivera"
                  />
                </div>

                {/* Field 2: Email */}
                <div className="space-y-1">
                  <label htmlFor="support-email" className="font-bold text-secondary uppercase tracking-wider block">
                    Email Address
                  </label>
                  <input
                    id="support-email"
                    type="email"
                    required
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    className="w-full bg-gray-50 border border-outline-variant/60 rounded-lg p-2.5 text-on-surface focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary text-xs"
                    placeholder="alex@rivera.com"
                  />
                </div>

                {/* Field 3: Subject */}
                <div className="space-y-1">
                  <label htmlFor="support-subject" className="font-bold text-secondary uppercase tracking-wider block">
                    Subject Topic
                  </label>
                  <select
                    id="support-subject"
                    value={formData.subject}
                    onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                    className="w-full bg-gray-50 border border-outline-variant/60 rounded-lg p-2.5 text-on-surface focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary text-xs select-none"
                  >
                    <option>Billing Inquiry</option>
                    <option>Hardware Installation Maintenance</option>
                    <option>Grid Connection Surcharge</option>
                    <option>General Care Feedback</option>
                  </select>
                </div>

                {/* Field 4: Message */}
                <div className="space-y-1">
                  <label htmlFor="support-message" className="font-bold text-secondary uppercase tracking-wider block">
                    Inquiry Details
                  </label>
                  <textarea
                    id="support-message"
                    required
                    rows={4}
                    value={formData.message}
                    onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                    className="w-full bg-gray-50 border border-outline-variant/60 rounded-lg p-2.5 text-on-surface focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary text-xs"
                    placeholder="Please write details about your support request..."
                  />
                </div>

                <button
                  id="support-submit-button"
                  type="submit"
                  className="w-full bg-primary text-white hover:bg-orange-850 py-3 rounded-lg font-bold text-xs cursor-pointer transition-all uppercase tracking-wider shadow-md hover:shadow-lg"
                >
                  Send Inquiry Message
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
